logging:
  level:
    org.fordes.adfs: info

application:
  rule:
    remote:
      - name: AdGuard 基础过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
        type: easylist

      - name: Loyalsoldier/clash-rules 广告域名列表
        path: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
        type: clash

      - name: 1Hosts mini
        path: https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/hosts.txt
        type: hosts

      - name: anti-ad smartdns
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
        type: smartdns

      - name:
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
        type: dnsmasq

  output:
    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
