name: Update Filters
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_en.md'
      - '.github/**'
      - '.devcontainer/**'
      - 'LICENSE'
  schedule:
    - cron: '0 12,20 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  Update_Filters:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Jar
        run:  mvn spring-boot:run

      - name: Get Current Timestamp
        id: timestamp
        env:
          TZ: Asia/Shanghai
        run: echo "::set-output name=datetime::$(date '+%Y-%m-%d %H:%M:%S %Z')"

      - name: Pull remote changes
        run: git pull --rebase origin now
        
      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🚀 CI Updated on ${{ steps.timestamp.outputs.datetime }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
